(in-package #:pzmq)
(include "zmq.h")
(ctype size "size_t")
(cstruct %msg "zmq_msg_t")
(constantenum
 c-errors
;;; awk -F '[*:]' '/\*E.+\*::/ {print $2}' doc/* | sort | uniq | awk '{print " ((:" tolower($1),  "\"" $1 "\"))"}' | xclip
 ((:eaddrinuse "EADDRINUSE"))
 ((:eaddrnotavail "EADDRNOTAVAIL"))
 ((:eagain "EAGAIN"))
 ((:efault "EFAULT"))
 ((:efsm "EFSM"))
 ((:ehostunreach "EHOSTUNREACH"))
 ((:eintr "EINTR"))
 ((:einval "EINVAL"))
 ((:emfile "EMFILE"))
 ((:emthread "EMTHREAD"))
 ((:enocompatproto "ENOCOMPATPROTO"))
 ((:enodev "ENODEV"))
 ((:enoent "ENOENT"))
 ((:enomem "ENOMEM"))
 ((:enotsock "ENOTSOCK"))
 ((:enotsup "ENOTSUP"))
 ((:eprotonosupport "EPROTONOSUPPORT"))
 ((:eterm "ETERM")))
